/* eslint-disable react/button-has-type */
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from 'styles/Home.module.scss';

import dynamic from 'next/dynamic';
import RateLimitChart from 'components/Button/RateLimitChart';
import RateLimitIndicator from 'components/RateLimitStatus';

const ConnectButton = dynamic(() => import('../components/Button/ConnectButton'), {
  ssr: false
});

const Home: NextPage = () => (
  <>
    <Head>
      <title>Turborepo Web3 Starter Kit</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <div className={styles.description}>
        <p>
          <code className={styles.code}>Protocol Rate Limit Guardian</code>
        </p>
        <ConnectButton />
      </div>

      <div></div>
      <div className={styles.center}>
        <h1 className="mx-2 text-3xl font-semibold">
          {' '}
          <RateLimitIndicator />
          <br />
          TVL 250.3M{' '}
        </h1>
        <RateLimitChart />
      </div>

      <div className={styles.grid}>
        <a className={styles.card} target="_blank" rel="noopener noreferrer">
          <h2>🌱 Override Rate Limit</h2>
          <p>If this was a false positive, you can override the rate limit and allow withdrawls.</p>
        </a>
        <a className={styles.card} target="_blank" rel="noopener noreferrer">
          <h2>⚡ Extend Timeout</h2>
          <p>If you need more time to assess the situation, you can extend the timeout period.</p>
        </a>

        <a className={styles.card} target="_blank" rel="noopener noreferrer">
          <h2>📦 Migrate Contract</h2>
          <p>If you need to migrate the contract, you can do so here.</p>
        </a>

        <a className={styles.card} target="_blank" rel="noopener noreferrer">
          <h2>🚫 Hault Protocol</h2>
          <p>
            If you need to hault the protocol, you can do so here. This will prevent any new
            deposits and withdrawls.
          </p>
        </a>
      </div>
    </main>
  </>
);

export default Home;
