/* eslint-disable react/button-has-type */
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from 'styles/Home.module.scss';

import dynamic from 'next/dynamic';
import RateLimitChart from 'components/RateLimitChart';
import RateLimitIndicator from 'components/RateLimitStatus';
import {
  HStack,
  Img,
  Table,
  TableCaption,
  TableContainer,
  Tbody,
  Td,
  Text,
  Tfoot,
  Th,
  Thead,
  Tr,
  VStack
} from '@chakra-ui/react';
import ActionGrid from 'components/ActionGrid';
import { TokenTable } from 'components/TokenTable';
import { useSwitchNetwork } from 'wagmi';

const ConnectButton = dynamic(() => import('../components/Button/ConnectButton'), {
  ssr: false
});

const Home: NextPage = () => {
  const network = useSwitchNetwork({
    chainId: 97
  });

  return (
    <>
      <Head>
        <title>Gaurdian Console</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HStack width={'100%'} justifyContent={'space-between'}>
          <p>
            <code className={styles.code}>Protocol Rate Limit Guardian</code>
          </p>
          <ConnectButton />
        </HStack>

        <div></div>
        <VStack>
          <RateLimitIndicator />
          <HStack>
            <RateLimitChart />
            <TokenTable />
          </HStack>
        </VStack>

        <ActionGrid />
      </main>
    </>
  );
};

export default Home;
