/* eslint-disable react/button-has-type */
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from 'styles/Home.module.scss';

import dynamic from 'next/dynamic';
import RateLimitChart from 'components/Button/RateLimitChart';
import RateLimitIndicator from 'components/RateLimitStatus';
import { HStack, Img, Text, VStack } from '@chakra-ui/react';
import ActionGrid from 'components/ActionGrid';

const ConnectButton = dynamic(() => import('../components/Button/ConnectButton'), {
  ssr: false
});

const Home: NextPage = () => (
  <>
    <Head>
      <title>Turborepo Web3 Starter Kit</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <div className={styles.description}>
        <p>
          <code className={styles.code}>Protocol Rate Limit Guardian</code>
        </p>
        <ConnectButton />
      </div>

      <div></div>
      <VStack>
        <HStack>
          <RateLimitIndicator />
        </HStack>
        <RateLimitChart />
      </VStack>

      <ActionGrid />
    </main>
  </>
);

export default Home;
